### ISSUE TITLE
Bisu sees the spreadsheet column titles in undercase

### ISSUE THREAD

**Issue by raphaelcruzeiro** [hole19/bisu#3]
If I have uppercase characters on my column title (e.g. `pt-BR`), Bisu will see it as `pt-br`. This will not match what's on traslatable.yml.

```
[ERROR] Unknown language pt-BR
```

**Comment by joaoffcosta** [comment]
Thanks for reporting! Fixed in [1.4.5](https://github.com/hole19/bisu/releases/tag/v1.4.5)
